### ISSUE TITLE
Not working with Yarn Workspaces

### ISSUE THREAD

**Issue by thekevinbrown** [prettier-solidity/prettier-plugin-solidity#317]
I'm seeing #196 with "prettier-plugin-solidity": "1.0.0-alpha.55" We're using yarn workspaces.

I can't share the source at the moment. Anything I can do to debug?

```
$ prettier --write **/*.sol **/*.ts
[error] No parser could be inferred for file: contracts/Loggable.sol
...etc...
error Command failed with exit code 2.
```

**Comment by fvictorio** [comment]
According to [the docs](https://prettier.io/docs/en/plugins.html#using-plugins):

> Plugins are automatically loaded if you have them installed in the same node_modules directory where prettier is located.

So maybe the problem is that `prettier` is being hoisted but `prettier-plugin-solidity` it's not. Two things come to mind (but I don't know a lot about yarn workspaces):

- Prettier has a `--plugin-search-dir` that you could use. I guess it would be something like `--plugin-search-dir ../node_modules` or maybe `--plugin-search-dir packages/contracts/node_modules`, I'm not sure.
- Maybe you can configure yarn to avoid hoisting `prettier`, or force it to hoist `prettier-plugin-solidity` so that they are in the same `node_modules`?

**Comment by thekevinbrown** [comment]
Ah, this is kind of a pain. Is there a way to use two plugin search directories?

We're using buidler, which doesn't support having its deps hoisted, but also we're using prettier on all the packages, so we end up with two instances of prettier, one in our smart contracts package, and another hoisted one. We don't really want to install prettier-plugin-solidity in the workspace package json if we can avoid it, but I suppose we could have both if we have to.

**Comment by fvictorio** [comment]
Just in case, buidler added support for workspaces in 1.4.5: https://github.com/nomiclabs/buidler/issues/468#issuecomment-685865431 :slightly_smiling_face:

**Comment by fvictorio** [comment]
Also, again according to the docs:

> Tip: You can set --plugin or --plugin-search-dir options multiple times.

**Comment by thekevinbrown** [comment]
It was indeed our smart-contracts buidler package that is hoisted, so looks like the easiest thing to do there is just upgrade buidler, then turn off the hoisting.

**Comment by mattiaerre** [comment]
it seems we can close this issue right @thekevinbrown ? thanks for your help @fvictorio

**Comment by thekevinbrown** [comment]
Yup.

**Comment by chapati23** [comment]
Had the same problem when setting up a project with yarn v2. What worked for me was to set `nodeLinker: "node-modules"` in `.yarnrc.yml`: https://yarnpkg.com/configuration/yarnrc#nodeLinker

**Comment by JasoonS** [comment]
Somewhat related, with `pnpm` I had to use the `--plugin=prettier-plugin-solidity` flag.

**Comment by Janther** [comment]
@JasoonS this appears to be an issue with prettier. prettier/prettier#9167
