### ISSUE TITLE
don't break import lines

### ISSUE THREAD

**Issue by adjicf** [prettier-solidity/prettier-plugin-solidity#331]
Long import lines are prettified from:

```
import {OwnableUpgradeSafe} from "@openzeppelin/contracts-ethereum-package/contracts/access/Ownable.sol";
```

to:
```
import {
    OwnableUpgradeSafe
} from "@openzeppelin/contracts-ethereum-package/contracts/access/Ownable.sol"
```;

Solc doesn't like it. It is easy to fix with a `// prettier-ignore`, but probably is better to leave the line untouched.

**Comment by fvictorio** [comment]
I thought this was supported by solc, am I wrong?

**Comment by petejkim** [comment]
I've run into issues with the compiler (0.6.12) not liking multi-line import statements under certain conditions.

**Comment by fvictorio** [comment]
I'm not sure what to do about this. Options are:

1. Keep the current behavior, since this works in newer versions of solc (I think?)
2. Be conservative and never split imports
3. Add a configuration option for this

I'd rather not add an option, and 1 seems like being an asshole to people stuck in older versions. I think the correct solution here is 2 for now, and then we should move to 1 or 3 depending on how common is to be using a solc version that doesn't support multi-line imports.
