### ISSUE TITLE
Official Solidity Style Guide Divergence

### ISSUE THREAD

**Issue by gitpusha** [prettier-solidity/prettier-plugin-solidity#361]
Hi everyone, 

Nice work! Thank you first of all. 

One thing that bugged me the last time I used this plugin some while ago was that the auto-formatted style diverges quite far from the official Solidity [Style Guide.](https://solidity.readthedocs.io/en/latest/style-guide.html) 

Notably in the [function declaration modifier](https://solidity.readthedocs.io/en/latest/style-guide.html#function-declaration) parts for example:

![image](https://user-images.githubusercontent.com/36712489/95470090-a85c0980-0980-11eb-8b41-ef61e4fb69fe.png)

Where this plugin formats the modifiers onto the same line, like here for example:
![image](https://user-images.githubusercontent.com/36712489/96169908-2db46080-0f23-11eb-9d0d-bcaa74cb55f4.png)

**Are there any plans for this plugin to follow the official Style Guide more closely, or was this done deliberately?**

**Comment by fvictorio** [comment]
I think our (non-written) philosophy is: follow the style guide when it makes sense, but ignore it if there's a good reason, especially if a lot of good production code doesn't follow it for something.

Another non-written rule, but this one mostly mine, is: "what would open zeppelin do" :stuck_out_tongue: 

Modifiers are particularly tricky because there doesn't seem to be a consensus on how to write them. There were several discussions around this. I personally think this is one of those "no one is going to be happy" things. This doesn't mean that it couldn't be improved!

Btw, notice that the plugin *will* put them in separate line if there are many of them, so it kind of follows the style guide but only for breaking the line.

**Comment by gitpusha** [comment]
Ok makes sense. After using `prettier-plugin-solidity` for 3 weeks now I am also happy with the divergence. All good :)
