### ISSUE TITLE
Remove unused imports

### ISSUE THREAD

**Issue by moodysalem** [prettier-solidity/prettier-plugin-solidity#396]

**Comment by fvictorio** [comment]
You mean removing solidity imports that are not being used? I don't think that's something this project will do. A formatter should never modify the AST of the code (so: not adding or removing things, except syntactically unimportant things like whitespace or parentheses).

I actually want to do a solhint plugin for this some day, but I haven't yet because it's not trivial.

Closing this, but please re-open if you meant something else!

**Comment by moodysalem** [comment]
Yes, it doesn't seem that crazy to be part of the prettier plugin, maybe behind a flag? But yeah some kind of support would be greatly appreciated!
https://openbase.io/js/prettier-plugin-organize-imports/documentation

**Comment by fvictorio** [comment]
I'm definitely thing this will happen somewhere, just not in this plugin. I will (try to remember to) comment on this issue if I end up doing this as a solhint plugin though!
