### ISSUE TITLE
Declare each parameter, modifier, and return value on its own line

### ISSUE THREAD

**Issue by yosriady** [prettier-solidity/prettier-plugin-solidity#454]
How do I configure the plugin to declare each parameter, modifier, and return value on its own line? For example:

```solidity
function foo(
  address[] bars
)
  external
  myModifier(_bars.length, msg.sender)
  returns (
    address baz,
    bool bam
  )
{
...
}
```

Currently, if you run `prettier`, it'll format the above to a single line:

```solidity
function foo(address[] bars) external myModifier(_bars.length, msg.sender) returns (address baz,	bool bam) {
...
}
```

Here is my `.prettierrc`:

```json
{
  "arrowParens": "avoid",
  "bracketSpacing": true,
  "endOfLine":"auto",
  "printWidth": 120,
  "singleQuote": false,
  "tabWidth": 2,
  "trailingComma": "all",
  "overrides": [
    {
      "files": "*.sol",
      "options": {
        "tabWidth": 2
      }
    }
  ]
}

```

**Comment by mattiaerre** [comment]
thanks for reporting this issue @yosriady we'll take a look

**Comment by Janther** [comment]
Hi @yosriady,

The only configuration we offer, other than the ones supported by Prettier, is `explicitTypes` as you can see in this [file](https://github.com/prettier-solidity/prettier-plugin-solidity/blob/master/src/options.js).

There have been many discussions around the proper formatting of function declarations as is the most complex and versatile syntax in solidity.
We don't want to provide a configuration as it will lead to a complex implementation of the printer so mainly we do follow the rule of `printWidth`, if the line is longer than those characters, then we proceed to split and indent whatever is inside.
Another rule we follow is that if a child splits, then the parent will split too.

In terms of the params within a function declaration we agreed that this was too confusing as some declarations would split while other would stay in one line just because of the length. So we decided to split when the number of params would be [greater than 2](https://github.com/prettier-solidity/prettier-plugin-solidity/issues/256#issuecomment-610074187).

We welcome the conversation as we would like to know what the community wants and are willing to change.

**Comment by mds1** [comment]
Hello!

> so mainly we do follow the rule of `printWidth`, if the line is longer than those characters, then we proceed to split and indent whatever is inside.

> In terms of the params within a function declaration we agreed that this was too confusing as some declarations would split while other would stay in one line just because of the length. So we decided to split when the number of params would be [greater than 2](https://github.com/prettier-solidity/prettier-plugin-solidity/issues/256#issuecomment-610074187).

My understanding from the linked discussion here is that first you split function declarations at greater than 2 parameters, then fallback to max line width, and this seems to be the behavior I see.

But I expected (and personally would prefer) the opposite ordering here—try to keep things to one line, but split parameters if it'd exceed `printWidth`. I actually found this issue because I thought the behavior I was seeing was a bug, since things were being formatted to multiple lines even though they fit well within `printWidth`

This "unexpected" formatting happens to me a lot, especially in constructors which have no modifiers. So you can have the function declaration for short constructors like the one below take up 6 lines even when it'd be < 80 characters on one line

```solidity
// Current
constructor(
  uint256 _min,
  uint256 _max,
  address _token
  address _admin
) {
  ...
}

// Expected
constructor(uint256 _min, uint256 _max, address _token, address _admin) {
  ...
}
```

All that to say, since you asked want the community wants, I just wanted to chime in to mention that I definitely prefer prioritizing the `printWidth` checks first and only splitting parameters when necessary 😁

**Comment by fvictorio** [comment]
I agree with @mds1, but I guess the real question is how do we gauge what the community wants with respect to this. This is exactly the kind of thing we should have more or less defined before getting a stable release. A lot of big projects are using `prettier-solidity` now, so I'll ask the ones I know and see if we get some consensus on this.

**Comment by fvictorio** [comment]
Closing this in favor of #474.
