### ISSUE TITLE
Non-breaking import statements is ugly and causes trouble with solhint rules

### ISSUE THREAD

**Issue by gitpusha** [prettier-solidity/prettier-plugin-solidity#533]
See formatting change that was recently introduced to support older versions of solc: #331

I am always using newer versions of solc and for me I don't wanna upgrade to new versions of prettier-plugin-solidity, unless there is an option to allow for import syntax line breaks. 

The long lines look really ugly (not prettier 😉  )  and also it clashes with my `solhint` rules like `max-lines` . 

I think the default option should be to allow for line breaks as in previous versions of prettier-plugin-solidity. 

Devs that are using older versions of solidity should have the option to disable the line-breaks with an option. 

But that's my `prettier` bias - I would also be ok with having it ugly by default as long as I can make it pretty with an option. 

Love the tool, thx for all the great work!

**Comment by Janther** [comment]
Hi,
Just letting you know that we are working on this #535 and there's a lot of progress being made.
Adding a new Configurable Option is not something we take lightly so we are being very careful with this sort of requirements.

**Comment by Janther** [comment]
Hi @gitpusha,
We just released a new version that supports the `compiler` option.
As long as the version is greater or equal to `0.7.4` the format will split imports when needed. Otherwise, they will be kept in a single line.

**Comment by gitpusha** [comment]
Cool thanks!

**Comment by gitpusha** [comment]
Hi @Janther - I have some files in `pragma solidity 0.8.6;` and when I format them with  `yarn prettier --write .` it seems that prettier-plugin-solidity one-lines the import statements again, even though I thought that the tool would by default split imports for files gte `0.7.4` ? 

Weirdly I noticed that when I used my VS code editors `format document` command it works and the `.sol` files gte `0.7.4` import statements will be split.

**Comment by Janther** [comment]
VS code ships with a static version of the plugin and it's not always up to date. In your installation it did split the imports because it probably had a version of our plugin where we hadn't addressed the bug with imports in one line.

As for the compiler version, we feel that automatically discovering the version through the `pragma` statement will involve too much maintenance on a feature that we still consider experimental and where the benefits are minimal.

The compiler option right now only checks for 2 breakpoints, `0.7.4` for imports and `0.8.0` for deciding wether to use `byte`/`bytes1` or how to parenthesise the exponentiation of an exponentiation `a**b**c`.
If you only care about the import statement using `0.7.4` as a compiler version should be enough.

we will consider expanding the option to also accept ranges.

**Comment by gitpusha** [comment]
Ok thanks! 

I got it to work with the overrides options.
