### ISSUE TITLE
issue w/ for statement

### ISSUE THREAD

**Issue by mattiaerre** [prettier-solidity/prettier-plugin-solidity#64]
# Description

missing a semicolon if for statement body is not included in braces.

## Source

```javascript
  function count(string[] data) public pure returns (uint) {
    uint result;
    for(uint i = 0; i < data.length; i++)
      result += 1;
    return result;
  }
```

## Prettified

```javascript
  function count(string[] data) public pure returns(uint) {
    uint result;
    for (uint i = 0; i < data.length; i++) result += 1
    return result;
  }
```

> N.B. there is a missing `;` at the end of the for body

**Comment by fvictorio** [comment]
Just repeating what we've already said elsewhere. The problem seems to be here:

https://github.com/prettier-solidity/prettier-plugin-solidity/blob/642841458ebc73b2e2981c23f80d61e125cd384e/src/printer.js#L164-L170

where we add a semicolon only if the parent node is *not* a for statement. But if we don't do this, then an extra semicolon is added to the loop condition, because that is an `ExpressionStatement` too.

An extremely ugly fix would be to mutate the node so that the print function knows if it should add the semicolon. I don't like this, but it could work.

Another idea is to never add a semicolon in the `ExpressionStatement` printer, and make that a responsibility of the parent node.

**Comment by fvictorio** [comment]
The more I think about this, the more convinced I am that this is a problem upstream, so I opened https://github.com/federicobond/solidity-parser-antlr/issues/39 to see if it can be changed. But this may be a breaking change, so I don't know if it will be modified/fixed.

I say we do this: if the parser is modified and that allows us to do a proper fix, we do that. If not, let's do the easy/mutating approach, and revisit it later if needed.

**Comment by mattiaerre** [comment]
shall we decorate our parser so that it returns the structure we think it's more beneficial for us? that be also another option what do you think?

**Comment by fvictorio** [comment]
That's a great idea. Let's do that for now.
