### ISSUE TITLE
format fallback function err

### ISSUE THREAD

**Issue by angerpeanut** [prettier-solidity/prettier-plugin-solidity#659]
before format:
```
    fallback(bytes calldata _input) external {
    }
```
after format:
```
fallback() external {}
```

prettier version:
```
"prettier": "^2.6.1",
"prettier-plugin-solidity": "^1.0.0-beta.19",
```

**Comment by fvictorio** [comment]
Ugh, thanks for reporting this @angerpeanut. It also removed the `returns (...)` part of the signature.

**Comment by Oighty** [comment]
It looks like this might be an issue in the parser the plugin uses instead of the plugin itself. The parser is not providing the parameters and returnParameters in the node context when it identifies the `fallback` keyword.

https://github.com/solidity-parser/parser/blob/1a7bfb8752821945f894d47cbe588d1b0478541d/src/ASTBuilder.ts#L342

I believe setting the parameter and returnParameter values in the fallback case block in the same way they are set in the function case would resolve. 

```
parameters = ctx
  .parameterList()
  .parameter()
  .map((x) => this.visit(x))
returnParameters =
  ctxReturnParameters !== undefined
    ? this.visitReturnParameters(ctxReturnParameters)
    : null
```

Thoughts?

**Comment by fvictorio** [comment]
@Oighty you are probably right. Can you open an issue in [solidity-parser/parser](https://github.com/solidity-parser/parser/) please? I'll try to get it fixed as soon as I have some time.

**Comment by fvictorio** [comment]
Version 0.14.3 of the parser fixes this, so we just need to update the version of the parser used by prettier-solidity and add a test case for this (PRs welcome!)

**Comment by fvictorio** [comment]
Can the `receive` function have arguments? I mean, it makes sense for it to have them, but the latest docs say:

> A contract can have at most one receive function, declared using receive() external payable { ... } (without the function keyword). This function cannot have arguments, cannot return anything and must have external visibility and payable state mutability.
