### ISSUE TITLE
Migrate to Prettier v3

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier-solidity/prettier-plugin-solidity#747]
Hi, I am a maintainer at Prettier.

The Prettier team is currently working on v3(still alpha).
v3 will include breaking changes to the plugin interface.
Please see https://github.com/prettier/prettier/releases/tag/3.0.0-alpha.2 for more information.

I created this issue to help major plugins migrate to Prettier v3.

Myself and @fisker have created a migration guide which you can see here:

https://github.com/prettier/prettier/wiki/How-to-migrate-my-plugin-to-support-Prettier-v3%3F

If you have any questions, feel free to mention us. We can help you.

If you have already migrated to Prettier v3, sorry but please close this issue.

**Comment by fvictorio** [comment]
Hi @sosukesuzuki!

No, we haven't migrated yet. Thanks for sharing the guide, we'll let you know if you have questions.

**Comment by Janther** [comment]
Thank you @sosukesuzuki,

we do have a branch [preparing-parser-for-v3](https://github.com/prettier-solidity/prettier-plugin-solidity/tree/preparing-parser-for-v3) that is ready for V3, I'll have a look into what you documented for more details we might have missed.

Also to make our tests run we had to look into how `prettier:next` tests evolved and the addition of `jest-light-runner` was crucial since `jest` behaves really funny with `.mjs` files. You might add that to your document.

**Comment by fisker** [comment]
Interesting, your change in tests looks good. But I don't think lots of plugins do similar tests, so I think we'll skip document that.

**Comment by fisker** [comment]
You may missed, but I don't think `moduleNameMapper` works for `jest-light-runner`, so `TEST_STANDALONE` maybe not working.

**Comment by fisker** [comment]
Another thing I noticed, `jest-light-runner` supposed to be way faster than the built-in runner, but your tests seem slower in `preparing-parser-for-v3` branch, maybe there is something wrong.

**Comment by fisker** [comment]
> for some reason clean doesn't iterate over comments.

This works as expected. Since `comment` is not considered a "node".

**Comment by Janther** [comment]
> Another thing I noticed, `jest-light-runner` supposed to be way faster than the built-in runner, but your tests seem slower in `preparing-parser-for-v3` branch, maybe there is something wrong.

What test are you running?
`cross-env FULL_TEST=1 jest` does run the full suite in a similar way `prettier` does. But we also compile and compare the byte code for some tests that on purpose do change the AST. That makes them slower. in my experience using `jest-light-runner` is indeed way faster.

**Comment by Janther** [comment]
> You may missed, but I don't think `moduleNameMapper` works for `jest-light-runner`, so `TEST_STANDALONE` maybe not working.

We aren't really supporting `TEST_STANDALONE` yet. There's an open PR that we are testing out at the moment.

**Comment by fisker** [comment]
> What test are you running?

I didn't run locally, I was checking "actions" tab, maybe I clicked wrong CI job.

**Comment by Janther** [comment]
Ah then yeah, it was the `FULL_TEST` one.

**Comment by fvictorio** [comment]
If we do this we would be "forcing" users to upgrade prettier to v3, right?

I'm ok with that, but I'm asking because we are trying to get our first stable version (v1.0.0) out there and we have two options:

1. We release it for Prettier v2, and later release a breaking version that works only with v3.
2. We release the v1.0.0 with support just for v3.

I personally prefer the first option, since v3 is still in alpha and we want to do this release soon-ish. But I'm not against waiting for a stable version of v3. I guess the two main variables to consider are what's the ETA for a stable v3 and how much of a hassle is for users to move from v2 to v3.

**Comment by fisker** [comment]
You can check `prettier.version` to make plugin compatible with old version.

**Comment by fvictorio** [comment]
Oh, interesting, so we can make it work with both v2 and v3. Thanks for the clarification!
