### ISSUE TITLE
Questionable function parameter formatting after upgrade to 1.0.0-rc.1

### ISSUE THREAD

**Issue by istankovic** [prettier-solidity/prettier-plugin-solidity#755]
After upgrading to `1.0.0-rc.1` we noticed a change in how prettier does parameter formatting:

```
--- /tmp/IMessenger-before.sol  2022-11-08 13:31:18.356270373 +0100
+++ /tmp/IMessenger-after.sol   2022-11-08 13:33:59.899598464 +0100
@@ -21,8 +21,8 @@
     ///
     /// @param caller The caller.
     /// @param courier The contract that is trying to deliver the message.
-    function callAllowed(address caller, address courier)
-        external
-        view
-        returns (bool);
+    function callAllowed(
+        address caller,
+        address courier
+    ) external view returns (bool);
 }
```

This is using the default 80 chars line length, which the function parameters certainly fit in.
The whole function signature, including the modifiers, would be 87 characters in total, which would be over the limit.
However, shouldn't the parameters be split only if _they_ not fit the max line length, i.e. shouldn't the modifiers be ignored when looking at parameters? At least that has been my understanding after reading the release notes for `1.0.0-rc.1`.

**Comment by istankovic** [comment]
[IMessenger-before.sol.txt](https://github.com/prettier-solidity/prettier-plugin-solidity/files/9961202/IMessenger-before.sol.txt)
[IMessenger-after.sol.txt](https://github.com/prettier-solidity/prettier-plugin-solidity/files/9961203/IMessenger-after.sol.txt)

**Comment by fvictorio** [comment]
> However, shouldn't the parameters be split only if _they_ not fit the max line length, i.e. shouldn't the modifiers be ignored when looking at parameters?

Can you ellaborate on that? I'm not sure what you mean. What would be the ideal output for you here?

**Comment by istankovic** [comment]
> > However, shouldn't the parameters be split only if _they_ not fit the max line length, i.e. shouldn't the modifiers be ignored when looking at parameters?
> 
> Can you ellaborate on that? I'm not sure what you mean. What would be the ideal output for you here?

Well, I expected that the function parameters are not split but rather that the modifiers are, just like the old code (please see diff in the description). Essentially, in this particular case I would expect the code left unchanged.

**Comment by Janther** [comment]
This is an interesting one and there are many opinions.

The thing happening on function declarations is that there are 4 different lists of items that can be splitted into multiple lines to keep the format under the desired length.

1. Parameters
2. Modifiers
3. Arguments in modifier calls
4. Return parameters

We separated these into 2 levels

1. Parameters and Modifiers
2. Arguments in modifier calls and Return parameters

We split first parameters and modifiers and then if evaluate  case by case whether arguments in modifier calls and return parameters should be split.

Modifier calls and return parameters are very straight forward since each will only be split once they are in their own line but parameters and modifiers have 3 possible combinations.

1. Splitting everything if the signature surpasses the character length.
2. Splitting modifiers first
3. Splitting parameters first

The first option is a simple one and an overkill to be honest expanding simple signatures without the need.

The second one is the one proposed by @istankovic and we where using a variation of this in the beta version of the plugin. It is straight forward to implement and I see how this could be expected.

The last option and the one that we chose by having some feedback from the community places focus in the readability of the parameters first. This was slightly more complicated to achieve but the benefit on readability of the signature is appreciated.

This is one of the most controversial formatting decisions in this plugin so conversation around this is very welcomed.

**Comment by istankovic** [comment]
Thanks @Janther for the very nice explanation and the background behind the new behaviour!

I guess it comes down to personal preferences, as is often the case. In my case, I prefer the old formatting over the new one simply because the older one retains the nice flow when I read the code i.e. I do not need to immediately skip to the next line.
It also makes it easier to explain in the sense of "we start splitting as soon as we hit the line-width limit", according to this list:

> 1. Parameters
> 2. Modifiers
> 3. Arguments in modifier calls
> 4. Return parameters

But this is for sure a matter of preference and I appreciate different people having different views here.

**Comment by fvictorio** [comment]
@istankovic #630 is a different thing. It was about a previous behavior where we would always break a function signature into multiple lines if there were more than two parameters. That's no longer the case in v1.0.0.

Your issue, if I understood it correctly, is about preferring to break the modifiers into multiple lines instead of the parameters. This is something we were doing before, but for several reasons (feedback from users, a similar behavior to what prettier core does with typescript signatures) we switched to the current behavior.

I understand that it's annoying when a formatter does something in a different way as one would do it, but it's very unlikely that we'll make a decision that makes everyone happy. This, combined with the fact that we avoid adding options as much as possible (to keep the project simple), means that not everyone will like the result.

**Comment by istankovic** [comment]
> Your issue, if I understood it correctly, is about preferring to break the modifiers into multiple lines instead of the parameters. This is something we were doing before, but for several reasons (feedback from users, a similar behavior to what prettier core does with typescript signatures) we switched to the current behavior.

I see. Would it be possible, though, to have the old behaviour available as an option?
That would be useful to users who prefer the old line breaking algorithm.

**Comment by fvictorio** [comment]
In general we try to avoid adding options if possible. Each option we add makes the project harder to maintain, and this is just something we do on our free time so keeping it simple is important for us.
