### ISSUE TITLE
Add support for `prettier` `3.0`

### ISSUE THREAD

**Issue by pcaversaccio** [prettier-solidity/prettier-plugin-solidity#881]
Prettier `3.0` got [released](https://prettier.io/blog/2023/07/05/3.0.0.html) and I thought this plugin is ready, but after upgrading my repo [here](https://github.com/pcaversaccio/create-util) to `prettier` `3.0` I faced the following issue:

![image](https://github.com/sc-forks/solidity-coverage/assets/25297591/ac7f0fe9-ed69-4868-908e-75333cfada3f)

So there might be some additional work to be done.

**Comment by Janther** [comment]
Hi,

I tested with Prettier 3 and the issue is that prettier is no longer automatically checking installed packages.

for now you can use prettier 3.0.0 by adding a `.prettierrc.yml` file and declaring the plugin's name.

```YML
plugins:
  - "prettier-plugin-solidity"
```

I'll report the issue in the prettier repo but our plugin does support prettier 3.

**Comment by Janther** [comment]
Plugin automatic search feature has been removed from prettier so it has to be declared in the config file from now on.

https://prettier.io/blog/2023/07/05/3.0.0.html#plugin-search-feature-has-been-removed-14759httpsgithubcomprettierprettierpull14759-by-fiskerhttpsgithubcomfisker

**Comment by pcaversaccio** [comment]
@Janther thanks for investigation - I feel like this should be quickly documented in the `README` (or link it at least to this issue).

**Comment by Janther** [comment]
It's in the next PR #848
