### ISSUE TITLE
Incompatible with Prettier 3

### ISSUE THREAD

**Issue by Yurii921** [prettier-solidity/prettier-plugin-solidity#928]
prettier-plugin-solidity@1.1.3 conflicts with Prettier 3.0.3 during installation using `npm install`. (NodeJS v18.16.1 LTS; npm 9.8.1).

Please, add compatibility for Prettier 3.

**Comment by fvictorio** [comment]
Hi @Yurii921, I'm not sure what you mean by that. The latest version of `prettier-plugin-solidity` works fine with Prettier 3 as far as I can tell.

**Comment by SebastienGllmt** [comment]
Prettier v3 changed so that plugins are no longer automatically detected, and you have to manually add them (`prettier --plugin=prettier-plugin-solidit`)

You can also add the plugin to your `.prettierrc` file instead of having it be a command line argument, but that feature was broken until a very recent fix that is coming in prettier v3.1 (https://github.com/prettier/prettier/pull/15433)

**Comment by Yurii921** [comment]
> Prettier v3 changed so that plugins are no longer automatically detected, and you have to manually add them (`prettier --plugin=prettier-plugin-solidit`)
> 
> You can also add the plugin to your `.prettierrc` file instead of having it be a command line argument, but that feature was broken until a very recent fix that is coming in prettier v3.1 ([prettier/prettier#15433](https://github.com/prettier/prettier/pull/15433))

So it is because of `.prettierrc` not working. Thank you.
